services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        container_name: mosh-app
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            APACHE_RUN_USER: www-data
            APACHE_RUN_GROUP: www-data
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - mailpit
        networks:
            - mosh

    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: mosh-mysql
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - mosh

    mailpit:
        image: 'axllent/mailpit:latest'
        container_name: mosh-mailpit
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - mosh

networks:
    mosh:
        driver: bridge

volumes:
    mysql-data:
        driver: local
